services:
 web:
   build: dockerfiles/php-apache
   ports:
    - "80:80"
   volumes:
    - ./app:/var/www/html/app/public

 database:
  build: dockerfiles/mysql
  ports:
   - "3306:3306"
  volumes:
   - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
